version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "5000:5000" # Puerto interno de Gunicorn
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    depends_on:
      - app
    restart: always
